export const FILES_BACKUPS_LOAD_START = 'FILES_BACKUPS_LOAD_START'
export const FILES_BACKUPS_LOAD_SUCCESS = 'FILES_BACKUPS_LOAD_SUCCESS'
export const FILES_BACKUPS_LOAD_ERROR = 'FILES_BACKUPS_LOAD_ERROR'
