export const PROJECT_RESET = 'PROJECT_RESET'
export const PROJECT_LOAD_START = 'PROJECT_LOAD_START'
export const PROJECT_LOAD_SUCCESS = 'PROJECT_LOAD_SUCCESS'
export const PROJECT_LOAD_ERROR = 'PROJECT_LOAD_ERROR'
