export const FILES_LOAD_START = 'FILES_LOAD_START'
export const FILES_LOAD_SUCCESS = 'FILES_LOAD_SUCCESS'
export const FILES_LOAD_ERROR = 'FILES_LOAD_ERROR'

export const FILES_SAVE_START = 'FILES_SAVE_START'
export const FILES_SAVE_SUCCESS = 'FILES_SAVE_SUCCESS'
export const FILES_SAVE_ERROR = 'FILES_SAVE_ERROR'

export const FILES_DELETE_START = 'FILES_DELETE_START'
export const FILES_DELETE_SUCCESS = 'FILES_DELETE_SUCCESS'
export const FILES_DELETE_ERROR = 'FILES_DELETE_ERROR'

export const FILES_RUN_START = 'FILES_RUN_START'
export const FILES_RUN_SUCCESS = 'FILES_RUN_SUCCESS'
export const FILES_RUN_ERROR = 'FILES_RUN_ERROR'
