export const PROJECTS_INIT = 'PROJECTS_INIT'
export const PROJECTS_LOAD_START = 'PROJECTS_LOAD_START'
export const PROJECTS_LOAD_SUCCESS = 'PROJECTS_LOAD_SUCCESS'
export const PROJECTS_LOAD_ERROR = 'PROJECTS_LOAD_ERROR'

export const PROJECTS_SAVE_START = 'PROJECTS_SAVE_START'
export const PROJECTS_SAVE_SUCCESS = 'PROJECTS_SAVE_SUCCESS'
export const PROJECTS_SAVE_ERROR = 'PROJECTS_SAVE_ERROR'

export const PROJECTS_DELETE_START = 'PROJECTS_DELETE_START'
export const PROJECTS_DELETE_SUCCESS = 'PROJECTS_DELETE_SUCCESS'
export const PROJECTS_DELETE_ERROR = 'PROJECTS_DELETE_ERROR'
