export const DATABASES_LOAD_START = 'DATABASES_LOAD_START'
export const DATABASES_LOAD_SUCCESS = 'DATABASES_LOAD_SUCCESS'
export const DATABASES_LOAD_ERROR = 'DATABASES_LOAD_ERROR'

export const DATABASES_SAVE_START = 'DATABASES_SAVE_START'
export const DATABASES_SAVE_SUCCESS = 'DATABASES_SAVE_SUCCESS'
export const DATABASES_SAVE_ERROR = 'DATABASES_SAVE_ERROR'

export const DATABASES_DELETE_START = 'DATABASES_DELETE_START'
export const DATABASES_DELETE_SUCCESS = 'DATABASES_DELETE_SUCCESS'
export const DATABASES_DELETE_ERROR = 'DATABASES_DELETE_ERROR'

export const DATABASES_RUN_START = 'DATABASES_RUN_START'
export const DATABASES_RUN_SUCCESS = 'DATABASES_RUN_SUCCESS'
export const DATABASES_RUN_ERROR = 'DATABASES_RUN_ERROR'
