export const SERVERS_INIT = 'SERVERS_INIT'
export const SERVERS_LOAD_START = 'SERVERS_LOAD_START'
export const SERVERS_LOAD_SUCCESS = 'SERVERS_LOAD_SUCCESS'
export const SERVERS_LOAD_ERROR = 'SERVERS_LOAD_ERROR'

export const SERVER_SAVE_START = 'SERVER_SAVE_START'
export const SERVER_SAVE_SUCCESS = 'SERVER_SAVE_SUCCESS'
export const SERVER_SAVE_ERROR = 'SERVER_SAVE_ERROR'

export const SERVER_DELETE_START = 'SERVER_DELETE_START'
export const SERVER_DELETE_SUCCESS = 'SERVER_DELETE_SUCCESS'
export const SERVER_DELETE_ERROR = 'SERVER_DELETE_ERROR'
