export const DATABASE_BACKUPS_LOAD_START = 'DATABASE_BACKUPS_LOAD_START'
export const DATABASE_BACKUPS_LOAD_SUCCESS = 'DATABASE_BACKUPS_LOAD_SUCCESS'
export const DATABASE_BACKUPS_LOAD_ERROR = 'DATABASE_BACKUPS_LOAD_ERROR'
