export const PROFILE_LOAD_START = 'PROFILE_LOAD_START'
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS'
export const PROFILE_LOAD_ERROR = 'PROFILE_LOAD_ERROR'

export const PROFILE_LOGIN_START = 'PROFILE_LOGIN_START'
export const PROFILE_LOGIN_SUCCESS = 'PROFILE_LOGIN_SUCCESS'
export const PROFILE_LOGIN_ERROR = 'PROFILE_LOGIN_ERROR'

export const PROFILE_REGISTER_START = 'PROFILE_REGISTER_START'
export const PROFILE_REGISTER_SUCCESS = 'PROFILE_REGISTER_SUCCESS'
export const PROFILE_REGISTER_ERROR = 'PROFILE_REGISTER_ERROR'

export const PROFILE_LOGOUT_START = 'PROFILE_LOGOUT_START'
export const PROFILE_LOGOUT_SUCCESS = 'PROFILE_LOGOUT_SUCCESS'
export const PROFILE_LOGOUT_ERROR = 'PROFILE_LOGOUT_ERROR'
